### PR TITLE
[AR-4117] Change the fallback logo in wallet

### PR DESCRIPTION
**Pull request by karthik-durai**
# PR

## Describe your changes

1. Replace with new fallback logo and set it as data url.
2. The logo changes based on set theme(light and dark)

Screenshot 2022-09-14 at 12 55 27 PM
Screenshot 2022-09-14 at 12 55 39 PM
Screenshot 2022-09-14 at 12 55 50 PM
Screenshot 2022-09-14 at 12 55 56 PM

## Issue ticket number and link

- [AR-XXX](https://team-1624093970686.atlassian.net/browse/AR-XXX)
- [XXXX](https://github.com/arcana-network/auth/issues/XXXX)

## Checklist before requesting a review

- [X] You have performed a self-review of your own code
- [X] You are using approved terminology
- [X] Your changes have been tested locally
- [X] Your code builds clean without any errors or warnings

### CODE REVIEW

**Review by ajithranka — COMMENTED** [review]
The size on the logo on the bubble is quite small. Do you mind checking against the design and make it bigger if required?

**Comment by karthik-durai** [comment]
> The size on the logo on the bubble is quite small. Do you mind checking against the design and make it bigger if required?

@ajithranka increased width - https://github.com/arcana-network/auth/pull/87/commits/1204f6a000f84342a4fe199713b79502dbd3a6fa

Screenshot 2022-09-14 at 1 31 15 PM

increasing the height in the header increase the header height also, so left it as it was before.

Screenshot 2022-09-14 at 1 34 16 PM

**Review by makylfang — APPROVED** [review]

**Comment by ajithranka** [comment]
@karthik-durai I think we should ditch the background entirely in the svg and use only the inner logo. The background and the surrounding padding is making the logo look too small, especially on the frame header.

**Comment by karthik-durai** [comment]
> @karthik-durai I think we should ditch the background entirely in the svg and use only the inner logo. The background and the surrounding padding is making the logo look too small, especially on the frame header.

@ajithranka I thought of the same thing, will do it

**Comment by karthik-durai** [comment]
@ajithranka enlarged the image using figma and replaced it in code.

Screenshot 2022-09-14 at 3 43 45 PM
Screenshot 2022-09-14 at 3 43 55 PM
Screenshot 2022-09-14 at 3 44 25 PM
Screenshot 2022-09-14 at 3 44 33 PM

**Review by ajithranka — APPROVED** [review]
Perfect, thank you @karthik-durai!

**Pull request merged**
