### PR TITLE
Fix AR-3499 and fix for banner update that happened in main but not i…

### PR DESCRIPTION
**Pull request by shaloo**
…n dev not sure why

# PR

## Describe your changes

Readme - link update for SDK Ref Guide and banner update that somehow got missed in dev(?)

## Issue ticket number and link

- [AR-3499]

## Checklist before requesting a review

- [ ✅ ] You have performed a self-review of your own code
- [ ✅] You are using approved terminology
- [ ✅] Your changes have been tested locally
- [✅ ] Your code builds clean without any errors or warnings

### CODE REVIEW

**Comment by shaloo** [comment]
@makylfang this fix needs to go in dev and main branch of auth. C u pls review and approve?

**Comment by makylfang** [comment]
> @makylfang this fix needs to go in dev and main branch of auth. C u pls review and approve?

There was a similar PR with same changes which i merged. [PR](https://github.com/arcana-network/auth/pull/71)

**Comment by shaloo** [comment]
I see that in main branch, the banner update fix is already there but the link update for SDK reference guide under documentation section is missing.  If you click on that link it will say page not found. Should I delete this PR and issue another one for that?  Here is how I'm sharing doc fixes for auth now - issue PR to dev and assume you will merge them to main in the next release. Or should I be issuing 2 PRs separately for dev and main branch?

**Comment by shaloo** [comment]
Addressed via #78 closing this one.

**Pull request closed without merging**
